// Instruction files for agents without Claude-style skills (`smd skills install --target …`).
// Every target renders the same body (skills/agent-rules.md), so they never drift apart.
// Pure string functions: the CLI does the file I/O.

export const AGENT_TARGETS = ['claude', 'cursor', 'copilot', 'agents'] as const;
export type AgentTarget = (typeof AGENT_TARGETS)[number];
export type RulesTarget = Exclude<AgentTarget, 'claude'>;

/** Where the bundled CLI goes (relative to the project root) and how the rules tell agents to run it. */
export const SHARED_CLI_PATH = '.smd/smd.cjs';
export const SHARED_CLI_COMMAND = `node ${SHARED_CLI_PATH}`;

export const SECTION_START = '<!-- styled-markdown:start -->';
export const SECTION_END = '<!-- styled-markdown:end -->';

const DESCRIPTION = 'Read and write Styled Markdown (.smd) files with the smd CLI';

export interface TargetFile {
  /** Path relative to the project root, with forward slashes. */
  file: string;
  label: string;
  /** New file content, given the rules body and the file's current content (if any). */
  render: (body: string, existing?: string) => string;
}

export const TARGET_FILES: Record<RulesTarget, TargetFile> = {
  cursor: { file: '.cursor/rules/styled-markdown.mdc', label: 'Cursor rule for **/*.smd', render: cursorRule },
  copilot: {
    file: '.github/instructions/styled-markdown.instructions.md',
    label: 'Copilot instructions for **/*.smd',
    render: copilotInstructions,
  },
  agents: { file: 'AGENTS.md', label: 'styled-markdown section', render: (body, existing) => upsertSection(existing, body) },
};

/** `--target` values (repeatable, comma-separated) → distinct targets; `claude` when none are given. */
export function parseTargets(values: string[]): AgentTarget[] {
  const names = values.flatMap((v) => v.split(',')).map((v) => v.trim().toLowerCase()).filter(Boolean);
  const unknown = names.filter((n) => !(AGENT_TARGETS as readonly string[]).includes(n));
  if (unknown.length) throw new Error(`Unknown --target "${unknown[0]}". Use ${AGENT_TARGETS.join(', ')} (comma-separated or repeated).`);
  if (!names.length) return ['claude'];
  return [...new Set(names)] as AgentTarget[];
}

/** The shared rules with `{{smd}}` replaced by the command that runs the installed CLI. */
export function rulesBody(template: string, command = SHARED_CLI_COMMAND): string {
  return template.split('{{smd}}').join(command).trim() + '\n';
}

function generatedNote(target: RulesTarget): string {
  return `<!-- Generated by \`smd skills install --target ${target}\`. Re-run it to update. -->`;
}

export function cursorRule(body: string): string {
  const front = ['---', `description: ${DESCRIPTION}`, 'globs: **/*.smd', 'alwaysApply: false', '---'];
  return [...front, generatedNote('cursor'), '', body].join('\n');
}

export function copilotInstructions(body: string): string {
  const front = ['---', `description: "${DESCRIPTION}"`, 'applyTo: "**/*.smd"', '---'];
  return [...front, generatedNote('copilot'), '', body].join('\n');
}

/** The delimited AGENTS.md section. */
export function agentsSection(body: string): string {
  return [SECTION_START, generatedNote('agents'), '', body.trimEnd(), SECTION_END].join('\n');
}

/**
 * Inserts or replaces the styled-markdown section of an AGENTS.md file. Content outside the markers is kept as is;
 * a file without the section gets it appended. Throws when only one marker is present.
 */
export function upsertSection(existing: string | undefined, body: string): string {
  const eol = existing?.includes('\r\n') ? '\r\n' : '\n';
  const section = agentsSection(body).split('\n').join(eol);
  if (!existing?.trim()) return section + eol;
  const start = existing.indexOf(SECTION_START);
  const end = existing.indexOf(SECTION_END);
  if (start < 0 && end < 0) return appendSection(existing, section, eol);
  if (start < 0 || end < start) throw new Error(`AGENTS.md has a broken styled-markdown section: it needs ${SECTION_START} followed by ${SECTION_END}. Fix or remove the markers, then re-run.`);
  return existing.slice(0, start) + section + existing.slice(end + SECTION_END.length);
}

function appendSection(existing: string, section: string, eol: string): string {
  const trimmed = existing.replace(/\s+$/, '');
  return trimmed + eol + eol + section + eol;
}
